version: '3'
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["master", "50051"]
    tty: true
    stdin_open: true
    ports:
      - "50051:50051"
    networks:
      - cache_network

  slave:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["slave", "50051", "--master_ip", "master", "--master_port", "50051"]
    tty: true
    stdin_open: true
    networks:
      - cache_network
    restart: always
    depends_on: 
      - master

networks:
  cache_network: