# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xamples.proto\x12\tmypackage\"G\n\x0fWeatherResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04temp\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"`\n\rCoinsResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x64olar\x18\x02 \x01(\t\x12\x0c\n\x04\x65uro\x18\x03 \x01(\t\x12\n\n\x02uf\x18\x04 \x01(\t\x12\x0c\n\x04time\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x06 \x01(\t\"\x07\n\x05\x45mpty2\x86\x01\n\x04\x44\x61ta\x12@\n\x0eGetWeatherData\x12\x10.mypackage.Empty\x1a\x1a.mypackage.WeatherResponse\"\x00\x12<\n\x0cGetCoinsData\x12\x10.mypackage.Empty\x1a\x18.mypackage.CoinsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'examples_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_WEATHERRESPONSE']._serialized_start=29
  _globals['_WEATHERRESPONSE']._serialized_end=100
  _globals['_COINSRESPONSE']._serialized_start=102
  _globals['_COINSRESPONSE']._serialized_end=198
  _globals['_EMPTY']._serialized_start=200
  _globals['_EMPTY']._serialized_end=207
  _globals['_DATA']._serialized_start=210
  _globals['_DATA']._serialized_end=344
# @@protoc_insertion_point(module_scope)
