version: '3'
services:
  master:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: master
    command: ["master", "50051"]
    tty: true
    stdin_open: true
    volumes:
      - './app:/app'
    ports:
      - "50051:50051"
    networks:
      - cache_network

  slave:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: slave
    command: ["slave", "50051", "--master_ip", "master", "--master_port", "50051"]
    tty: true
    stdin_open: true
    volumes:
      - './app:/app'
    networks:
      - cache_network
    restart: always
    depends_on: 
      - master

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
        - "11211:11211"

networks:
  cache_network: